# Generated by Django 3.0.2 on 2020-02-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regis',
            name='q1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regis',
            name='q10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regis',
            name='q2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regis',
            name='q3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regis',
            name='q4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regis',
            name='q5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regis',
            name='q6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regis',
            name='q7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regis',
            name='q8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regis',
            name='q9',
            field=models.IntegerField(default=0),
        ),
    ]
