# Generated by Django 3.0.2 on 2020-02-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_ques'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ques',
        ),
    ]
